/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RetseptlarRouteImport } from './routes/retseptlar'
import { Route as MahsulotlarRouteImport } from './routes/mahsulotlar'
import { Route as KontaktlarRouteImport } from './routes/kontaktlar'
import { Route as KompaniyaRouteImport } from './routes/kompaniya'
import { Route as IndexRouteImport } from './routes/index'

const RetseptlarRoute = RetseptlarRouteImport.update({
  id: '/retseptlar',
  path: '/retseptlar',
  getParentRoute: () => rootRouteImport,
} as any)
const MahsulotlarRoute = MahsulotlarRouteImport.update({
  id: '/mahsulotlar',
  path: '/mahsulotlar',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktlarRoute = KontaktlarRouteImport.update({
  id: '/kontaktlar',
  path: '/kontaktlar',
  getParentRoute: () => rootRouteImport,
} as any)
const KompaniyaRoute = KompaniyaRouteImport.update({
  id: '/kompaniya',
  path: '/kompaniya',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kompaniya': typeof KompaniyaRoute
  '/kontaktlar': typeof KontaktlarRoute
  '/mahsulotlar': typeof MahsulotlarRoute
  '/retseptlar': typeof RetseptlarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kompaniya': typeof KompaniyaRoute
  '/kontaktlar': typeof KontaktlarRoute
  '/mahsulotlar': typeof MahsulotlarRoute
  '/retseptlar': typeof RetseptlarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kompaniya': typeof KompaniyaRoute
  '/kontaktlar': typeof KontaktlarRoute
  '/mahsulotlar': typeof MahsulotlarRoute
  '/retseptlar': typeof RetseptlarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kompaniya' | '/kontaktlar' | '/mahsulotlar' | '/retseptlar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kompaniya' | '/kontaktlar' | '/mahsulotlar' | '/retseptlar'
  id:
    | '__root__'
    | '/'
    | '/kompaniya'
    | '/kontaktlar'
    | '/mahsulotlar'
    | '/retseptlar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KompaniyaRoute: typeof KompaniyaRoute
  KontaktlarRoute: typeof KontaktlarRoute
  MahsulotlarRoute: typeof MahsulotlarRoute
  RetseptlarRoute: typeof RetseptlarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/retseptlar': {
      id: '/retseptlar'
      path: '/retseptlar'
      fullPath: '/retseptlar'
      preLoaderRoute: typeof RetseptlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mahsulotlar': {
      id: '/mahsulotlar'
      path: '/mahsulotlar'
      fullPath: '/mahsulotlar'
      preLoaderRoute: typeof MahsulotlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontaktlar': {
      id: '/kontaktlar'
      path: '/kontaktlar'
      fullPath: '/kontaktlar'
      preLoaderRoute: typeof KontaktlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kompaniya': {
      id: '/kompaniya'
      path: '/kompaniya'
      fullPath: '/kompaniya'
      preLoaderRoute: typeof KompaniyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KompaniyaRoute: KompaniyaRoute,
  KontaktlarRoute: KontaktlarRoute,
  MahsulotlarRoute: MahsulotlarRoute,
  RetseptlarRoute: RetseptlarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
